global:
  scrape_interval:     30s 
  evaluation_interval: 30s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['192.168.99.101:9308']
