{
 "title": "Kafka Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total handled scrape requests by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Kafka brokers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_brokers{instance=\"192.168.99.101:9308\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current number of Messages in the topic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{instance=\"192.168.99.101:9308\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Topic Partition replicas",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_topic_partition_replicas{instance=\"192.168.99.101:9308\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}